# code/benchmarks/cxr_classification/config_cxr.yaml
# Configuration for the Chest X-ray classification benchmark

data:
  # Path to the root directory of the CXR dataset (e.g., ChestX-ray14)
  # Contains metadata file and image folders
  path: "/path/to/your/cxr/dataset" # !!! IMPORTANT: Update this path !!!
  num_classes: 14 # Number of target classes (e.g., 14 for ChestX-ray14)

model:
  name: "densenet121"
  pretrained: true

training: # If QAT or fine-tuning is implemented
  epochs: 5
  learning_rate: 1e-4
  optimizer: "Adam"

quantization:
  methods: # List methods to evaluate: FP32, PTQ_INT8, BNB_INT8, BNB_NF4
    - "FP32"
    - "PTQ_INT8" # Requires calibration dataset
    - "BNB_INT8"
    # - "BNB_NF4" # Add if testing 4-bit
  calibration_samples: 100 # Number of samples for PTQ calibration

evaluation:
  batch_size: 32
  metrics: ["AUC", "InferenceTime", "Memory"]

output:
  # Directory to save results (relative to project root)
  dir: "results/processed"
  results_file: "cxr_benchmark_results.csv"
